# This makes it where players can't purchase any rank they want
# even if they can afford it. They must rank up through the ranks in order.
rankup-only: true

rankup-enabled: true
buy-rank-enabled: true
sign-rankup-enabled: true

groups:
  peasant: 1000
  knight: 2000
  lord: 3000
  king: 4000
  emperor: 5000